name: Robot data

# Cron pour faire fonctionner le script à 8h du matin
on:
 #push:
 #schedule:
  #- cron: "0 6 * * *"

permissions:
 contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runnerzz

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'
          
      - name: Install all necessary packages
        run: pip install requests pandas
        
      - name: trains
        run: python get_data.py

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
